.\" Process this file with
.\" groff -Tascii -man /path/tosource/lbackup.1 > outputfile.1
.\"
.TH LBACKUP 1 "04 MARCH 2010"
.SH NAME
lbackup - backup utility
.SH SYNOPSIS
/usr/local/sbin/lbackup </path/to/backup_configuration.conf>
.SH DESCRIPTION
.B
LBACKUP
is a backup utility designed to generate browsable,
hard linked, snapshot based backup sets from a 
specific directory. For details on configuration,
please refer to the LBackup website : 
http://www.lbackup.org

.SH BUGS
(1)
This man page is very basic. Please visit :
http://www.lbackup.org for the latest list 
of bugs and also more detailed documentation.

.SH AUTHOR
LBackup Team.

LBackup is protected by various licenses agreements.

Check http://lucidsystems.org for further details.

.SH CONTRIBUTIONS 
Various please visit the LBackup website for details.

.SH "SEE ALSO"
.BR bash (1),
.BR openssh (1),
.BR rm (1),
.BR mv (1),
.BR tee (1),
.BR python (1),
.BR ruby (1),
.BR sendmail (1),
.BR tcsh (1),
.BR mount (1),
.BR umount (1),
.BR grep (1),
.BR basename (1),
.BR echo (1),
.BR rsync (1),
.BR tail (1),
.BR awk (1)